auctions/urls.py
from django.urls import path

from . import views
app_name = 'auctions'

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name='create'),
    path("listing/<int:listing_id>/", views.listing, name='listing'),
    path("watchlist/", views.watchlist, name='watchlist'),
    path("bids/", views.bids, name='bids'),
    path("close/", views.close, name="close"),
    path("won/", views.won, name='won'),
    path("categories/", views.categories, name="categories"),
    path("category/<str:category>", views.category, name="category"),
    path("comments/", views.comments, name="comments")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class Listing(models.Model):
    title = models.CharField(max_length=25, null=True)
    category = models.CharField(max_length=15, null=True)
    img_url = models.TextField(null=True)
    description = models.TextField(null=True)
    starting_bid = models.FloatField(null=True)
    current_amt = models.FloatField(null=True)
    bid_status = models.CharField(max_length=10, null=True)
    created_by = models.CharField(max_length=25)
    timestamp = models.DateTimeField(null=True)
    won_by = models.CharField(max_length=25, null=True)


class Watchlist(models.Model):
    listing_id = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_id_watch")
    username = models.CharField(max_length=25)

class Bids(models.Model):
    listing_id = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_id_bids")
    username = models.CharField(max_length=25)
    bid_amt = models.FloatField(null=True)

class Comments(models.Model):
    listing_id = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listing_id_comm")
    username = models.CharField(max_length=25)
    timestamp = models.DateTimeField(null=True)
    comment = models.TextField(null=True)

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
from .models import Listing, Watchlist, Bids, Comments

from .models import User


def index(request):
    listing = list(Listing.objects.filter(bid_status="open"))
    return render(request, "auctions/index.html", {
        "listings": listing
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='/login')
def create(request):
    if request.method == 'GET':
        return render(request, "auctions/create.html")
    elif request.method == 'POST':
        title = request.POST['title']
        category = request.POST['category']
        img_url = request.POST['img_url']
        description = request.POST['description']
        starting_bid = request.POST['bid']
        current_amt = starting_bid
        bid_status = "open"
        created_by = request.user.username
        timestamp = datetime.datetime.now()
        #print(title)
        listings = Listing(title = title, category = category, img_url = img_url, description = description, starting_bid = starting_bid, current_amt = current_amt, bid_status = bid_status, created_by = created_by, timestamp = timestamp)
        listings.save()
        return HttpResponseRedirect(reverse("auctions:index"))
    
# @login_required(login_url='/login')
# def listing(request, listing_id):
#     if request.method == 'GET':
#         listing_data = list(Listing.objects.filter(id = listing_id))
#         return render(request, "auctions/listing.html", context={"listings":listing_data})
#     else:
#         pass

@login_required(login_url='/login')
def listing(request, listing_id):
    if request.method == 'GET':
        listing = list(Listing.objects.filter(id=listing_id))
        if listing[0].bid_status == 'close' and listing[0].won_by == request.user.username:
            return render(request, "auctions/listing.html", {"listings": listing, "won_check": "yes"})
        else:
            user_check = list(Listing.objects.filter(id=listing_id).filter(created_by=request.user.username).values('created_by'))
            creator = 0
            if len(user_check) == 0:
                creator = 1
            else:
                creator = 2
            watchlist_check = list(Watchlist.objects.filter(listing_id=listing_id).filter(username=request.user.username))
            statement = 0
            if len(watchlist_check) == 0:
                statement = 1
            else:
                statement = 2
            get_comments = list(Comments.objects.filter(listing_id=listing_id))
            return render(request, "auctions/listing.html", {
                "listings": listing,
                "statements":statement,
                "creators": creator,
                "comments": get_comments
            })

@login_required(login_url='/login')
def watchlist(request):
    if request.method == 'GET':
        watchlist_data = list(Watchlist.objects.filter(username=request.user.username))
        #print(len(watchlist_data))
        #print(watchlist_data[0].listing_id.id)
        watch_id_list = []
        for i in range(len(watchlist_data)):
            watch_id_list.append(watchlist_data[i].listing_id.id)
        watchlisting = list(Listing.objects.filter(id__in=watch_id_list))
        return render(request, "auctions/watchlist.html", {"watchlists":watchlisting})
    else:
        listing_id = request.POST.get("listing_id", False)
        listing_req = request.POST.get("listing_req", False)
        if listing_req == "0":
            #watchlist_check = list(Watchlist.objects.filter(listing_id=listing_id).filter(username=request.user.username))
            listing_obj = Listing.objects.get(id=listing_id)
            watchlist_save = Watchlist(listing_id=listing_obj, username=request.user.username)
            watchlist_save.save()

            watchlist_data = list(Watchlist.objects.filter(username=request.user.username))
            watch_id_list = []
            for i in range(len(watchlist_data)):
                watch_id_list.append(watchlist_data[i].listing_id.id)
            watchlisting = list(Listing.objects.filter(id__in=watch_id_list))
            return render(request, "auctions/watchlist.html", {"watchlists":watchlisting})
        else:
            watchlist_del = Watchlist.objects.get(listing_id=listing_id, username=request.user.username)
            watchlist_del.delete()
            watchlist_data = list(Watchlist.objects.filter(username=request.user.username))
            watch_id_list = []
            for i in range(len(watchlist_data)):
                watch_id_list.append(watchlist_data[i].listing_id.id)
            watchlisting = list(Listing.objects.filter(id__in=watch_id_list))
            return render(request, "auctions/watchlist.html", {"watchlists":watchlisting})

@login_required(login_url='/login')
def bids(request):
    if request.method == 'POST':
        bid_amt = int(request.POST['bid_amt'])
        listing_id = request.POST['listing_id']
        username = request.user.username
        bid_check = Listing.objects.filter(id=listing_id).values('current_amt')
        if bid_amt > bid_check[0]['current_amt']:
            user = Listing.objects.get(id=listing_id)
            user.current_amt = bid_amt
            user.save()
            listing_obj = Listing.objects.get(id=listing_id)
            new_bid = Bids(listing_id=listing_obj, username=request.user.username, bid_amt=bid_amt)
            new_bid.save()
            return HttpResponseRedirect(reverse("auctions:index"))
        else: 
            messages.error(request, 'ERROR: Bid amount must be higher than the current amount')
            return HttpResponseRedirect(reverse('auctions:listing', kwargs={'listing_id': listing_id}))
        # print(bid_check[0]['current_amt'])

@login_required(login_url='/login')
def close(request):
    if request.method == 'POST':
        listing_id = request.POST['listing_id']
        winnerlist = list(Bids.objects.filter(listing_id=listing_id).values('username', 'bid_amt').order_by('-bid_amt'))
        if len(winnerlist) != 0:
            winner = winnerlist[0]['username']
            listing_update = Listing.objects.get(id=listing_id)
            listing_update.bid_status = "close"
            listing_update.won_by = winner
            listing_update.save()
            return HttpResponseRedirect(reverse('auctions:index'))
        else:
            listing_update = Listing.objects.get(id=listing_id)
            listing_update.bid_status = "noWin"
            listing_update.save()
            return HttpResponseRedirect(reverse('auctions:index'))

@login_required(login_url='/login')
def won(request):
    if request.method == 'GET':
        wonbids = list(Listing.objects.filter(won_by=request.user.username).filter(bid_status="close"))
        if len(wonbids) != 0:
            return render(request, "auctions/bids_won.html", {"listings":wonbids})
        else:
            return render(request, "auctions/bids_won.html", {"message": "No bids won yet!"})


@login_required(login_url='/login')
def categories(request):
    if request.method == 'GET':
        return render(request, "auctions/categories.html", {"categories": ["phones", "laptops", "audio", "tablets", "accessories"]})


@login_required(login_url='/login')
def category(request, category):
    if request.method == 'GET':
        cat_listing = list(Listing.objects.filter(category=category).filter(bid_status="open"))
        return render(request, "auctions/category_page.html", {"listings": cat_listing})


@login_required(login_url='/login')
def comments(request):
    if request.method == 'POST':
        comment = request.POST['comment']
        listing_id = request.POST['listing_id']
        listing_obj = Listing.objects.get(id=listing_id)
        timestamp = datetime.datetime.now()
        comment_save = Comments(listing_id=listing_obj, username=request.user.username, timestamp=timestamp, comment=comment)
        comment_save.save()
        return HttpResponseRedirect(reverse('auctions:listing', kwargs={"listing_id": listing_id}))
        


    

auctions/templates/auctions/bids_won.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Bids Won</h2>
{% if message %}
    <p>No bids won yet</p>
{% endif %}
{% for listing in listings %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 mt-3">
                <div class="card">
                    <div class="card-horizontal" style="display: flex; flex: 1 1 auto;">
                        <div class="img-square-wrapper">
                            <img class="" src="{{ listing.img_url }}" alt="Card image cap" style="width: 300px; height: 300px; padding: 10px">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ listing.title }}</h4>
                            <p class="card-text">{{ listing.description }}</p>
                            <b>Winning Price: ₹ {{ listing.current_amt }}</b>
                            <br>
                            {{ listing.timestamp }}
                            <br>
                            <br>
                            <div class="alert alert-success" role="alert" style="width: fit-content;">
                                Congratulations! You won the bid!
                            </div>
                            <br>
                            <a href="{% url 'auctions:listing' listing.id %}" class="btn btn-primary">View Listing</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <br>
    <h3>Choose a Category</h3>
    <br>
    <div>
        {% for category in categories %}
        <a type="button" class="btn btn-outline-primary btn-lg btn-block" href="{% url 'auctions:category' category %}" style="text-transform: capitalize;">{{ category }}</a>
        {% endfor %}
        <!-- <a type="button" class="btn btn-primary btn-lg btn-block">Phones</a>
        <a type="button" class="btn btn-secondary btn-lg btn-block">Laptops</a>
        <a type="button" class="btn btn-success btn-lg btn-block">Audio</a>
        <a type="button" class="btn btn-warning btn-lg btn-block">Tablets</a>
        <a type="button" class="btn btn-danger btn-lg btn-block">Accessories</a> -->
    </div>
{% endblock %}

auctions/templates/auctions/category_page.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Category</h2>
<br>
{% for listing in listings %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="card">
                <div class="card-horizontal" style="display: flex; flex: 1 1 auto;">
                    <div class="img-square-wrapper">
                        <img class="" src="{{ listing.img_url }}" alt="Card image cap" style="width: 300px; height: 300px; padding: 10px">
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ listing.title }}</h4>
                        <p class="card-text">{{ listing.description }}</p>
                        <b>₹ {{ listing.current_amt }}</b>
                        <br>
                        {{ listing.timestamp }}
                        <br>
                        <a href="{% url 'auctions:listing' listing.id %}" class="btn btn-primary">View Listing</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create a Listing</h2>
    <br>
    <div>
        <form action="{% url 'auctions:create' %}" method="post" style="width: 500px; padding: 20px;">
            {% csrf_token %}
             <div class="form-group">
                <label for="exampleInputEmail1">Listing name</label>
                <input autofocus class="form-control" type="text" placeholder="Name" id="listing_name", name="title">
             </div>
             <br>
             <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <select name="category" autofocus class="form-control">
                    <option value="" disabled selected>Category</option>
                    <option value="phones">Phones</option>
                    <option value="laptops">Laptops</option>
                    <option value="audio">Audio</option>
                    <option value="tablets">Tablets</option>
                    <option value="accessories">Accessories</option>
                </select>
             </div>
             <br>
             <div class="form-group">
                <label for="exampleInputEmail1">Description</label>
                <textarea autofocus class="form-control" placeholder="Description" name="description"></textarea>
             </div>
             <br>
             <div class="form-group">
                <label for="exampleInputEmail1">Image URL</label>
                <input autofocus class="form-control" type="text" name="img_url" placeholder="Image URL">
            </div>
            <br>
            <div class="form-group">
                <label for="exampleInputEmail1">Starting Bid</label>
                <input autofocus class="form-control" type="text" name="bid" placeholder="Starting Bid">
            </div>
            <br>
            <div class="form-group" style="width: 100px;">
                <input autofocus class="form-control btn btn-primary" type="submit">
            </div>
        </form>
    </div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <br>
    {% for listing in listings %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 mt-3">
                <div class="card">
                    <div class="card-horizontal" style="display: flex; flex: 1 1 auto;">
                        <div class="img-square-wrapper">
                            <img class="" src="{{ listing.img_url }}" alt="Card image cap" style="width: 300px; height: 300px; padding: 10px">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ listing.title }}</h4>
                            <p class="card-text">{{ listing.description }}</p>
                            <b>₹ {{ listing.current_amt }}</b>
                            <br>
                            {{ listing.timestamp }}
                            <br>
                            <a href="{% url 'auctions:listing' listing.id %}" class="btn btn-primary">View Listing</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:won' %}">Bids Won</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Listing</h2>
{% for listing in listings %}
    <br>
    <div>
        <img src="{{ listing.img_url }}" style="width: 300px; height: 300px;">
        <br>
        <h4>{{ listing.title }}</h4>
        <b>Category: {{ listing.category }}</b>
        <br>
        <p>{{ listing.description }}</p>
        <br>
        <b>Created by: {{ listing.created_by }}</b>
        <br>
        <b>Listed on: {{ listing.timestamp }}</b>
        <br>
        <br>
        {% if won_check %}
        <div class="alert alert-success" role="alert" style="width: fit-content;">
            <h4 class="alert-heading">Congratulations! You successfully won the bid!</h4>
        </div>
        <br>
        {% else %}
        <h3><b>Current Price: ₹ {{ listing.current_amt }}</b></h3>
        <br>
        {% if creators == 2 %}
        <b>Original Price: ₹ {{ listing.starting_bid }}</b>
        {% endif %}
        <br>
        <br>
        {% if creators == 2 %}
            <form action="{% url 'auctions:close' %}" method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ listing.id }}" name="listing_id">
                <button autofocus class="form-control btn btn-primary" type="submit" style="width: fit-content;">Close Bid</button>
            </form>
        {% else %}
            <form action="{% url 'auctions:watchlist' %}" method="post" style="width: 500px;">
                {% csrf_token %}
                <input type="hidden" value="{{ listing.id }}" name="listing_id">
                {% if statements == 1 %}
                <input type="hidden" value="0" name="listing_req">
                <button autofocus class="form-control btn btn-primary" type="submit" style="width: fit-content;">Add to Watchlist</button>
                {% else %}
                <input type="hidden" value="1" name="listing_req">
                <button autofocus class="form-control btn btn-primary" type="submit" style="width: fit-content;">Remove from Watchlist</button>
                {% endif %}
                
            </form>
            <hr style="border: 1px solid;">
            <form style="width: 500px;" method="post" action="{% url 'auctions:bids' %}">
                {% csrf_token %}
                <h4>Place Bid</h4>
                <input type="hidden" value="{{ listing.id }}" name="listing_id">
                <input autofocus class="form-control" type="text" placeholder="Bid Amount" name="bid_amt">
                <br>
                <input autofocus class="form-control btn btn-primary" type="submit" style="width: 100px;">
            </form>
            {% if messages %}
            {% for message in messages %}
            {% if message.tags %}
            <br>
            <div class="alert alert-danger" role="alert">
                {{ message.message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            <hr style="border: 1px solid;">

            
        
        {% endif %}
        <br>
        <div>
            <h3>Comments:</h3>
            <br>
            <div>
                <form style="width: 500px;" method="post" action="{% url 'auctions:comments' %}">
                    {% csrf_token %}
                    <textarea autofocus class="form-control" placeholder="Comment" name="comment"></textarea>
                    <input type="hidden" value="{{ listing.id }}" name="listing_id">
                    <br>
                    <input type="submit" autofocus class="form-control btn btn-primary" value="Add Comment">
                </form>
            </div>
            <br>
            {% for comment in comments %}
            <div>
                <h6><b>Comment by {{ comment.username }}</b></h6>
                <h6>{{ comment.timestamp }}</h6>
                <p>{{ comment.comment }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
    </div>
    
        
{% endfor %}

    
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>
    <br>
    {% for watchlist in watchlists %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 mt-3">
                <div class="card">
                    <div class="card-horizontal" style="display: flex; flex: 1 1 auto;">
                        <div class="img-square-wrapper">
                            <img class="" src="{{ watchlist.img_url }}" alt="Card image cap" style="width: 300px; height: 300px; padding: 10px">
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ watchlist.title }}</h4>
                            <p class="card-text">{{ watchlist.description }}</p>
                            <b>₹ {{ watchlist.current_amt }}</b>
                            <br>
                            {{ watchlist.timestamp }}
                            <br>
                            <a href="{% url 'auctions:listing' watchlist.id %}" class="btn btn-primary">View Listing</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}